name: open_document_example
description: Demonstrates how to use the open_document plugin.
homepage: https://github.com/fabio21/open_document.git
repository: https://github.com/fabio21/open_document.git
version: 0.0.1

publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  open_document:
    path: ../

  cupertino_icons: ^0.1.3
  dio: ^4.0.0-beta7
  permission_handler: ^6.0.1+1
  wakelock: ^0.5.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true































