name: open_document
description: Opendocument generate a folder and open the pdf, xlsx, docs, ppt and zip files,
  you can also locate your MyFilesScreen implement file and for style use StyleMyFile.
version: 1.0.5

homepage: https://github.com/fabio21/open_document.git
repository: https://github.com/fabio21/open_document.git

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  archive: ^3.3.1
  flutter_slidable: ^2.0.0
  share_plus: ^4.0.10+1
  intl: ^0.17.0
  url_launcher: ^6.1.5
  plugin_platform_interface: ^2.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  dartdoc: ^6.0.1


flutter:
  plugin:
    platforms:
      android:
        package: com.fsconceicao.open_document
        pluginClass: OpenDocumentPlugin
      ios:
        pluginClass: OpenDocumentPlugin
      macos:
        pluginClass: OpenDocumentPlugin
      windows:
        pluginClass: OpenDocumentPlugin


































