name: open_document
description: OpenDocument generate a local folder, for file and document storage, also can open pdf, xlsx, docs, ppt and zip files.
  You can also locate your files by implementing MyFilesScreen you can change folder styles and colors using StyleMyFile
version: 1.0.6+2


homepage: https://github.com/fabio21
repository: https://github.com/fabio21/open_document.git
issue_tracker: https://github.com/fabio21/open_document/issues

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  archive: ^3.3.7
  flutter_slidable: ^3.0.0
  share_plus: ^7.0.2
  intl: ^0.18.1

  plugin_platform_interface: ^2.1.4


dev_dependencies:
  flutter_test:
    sdk: flutter
  dartdoc: ^6.3.0


flutter:
  plugin:
    platforms:
      android:
        package: com.fsconceicao.open_document
        pluginClass: OpenDocumentPlugin
      ios:
        pluginClass: OpenDocumentPlugin
      macos:
        pluginClass: OpenDocumentPlugin
      windows:
        pluginClass: OpenDocumentPlugin


































