name: open_document
description: A new flutter plugin project.
version: 1.0.0
homepage: https://github.com/fabio21/open_document.git
repository: https://github.com/fabio21/open_document.git

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  archive: ^3.1.2
  flutter_slidable: ^0.6.0-nullsafety.0
  path_provider_windows: ^2.0.0
  share_plus: ^2.1.0
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.example.open_document
        pluginClass: OpenDocumentPlugin
      ios:
        pluginClass: OpenDocumentPlugin
      macos:
        pluginClass: OpenDocumentPlugin


































